### ISSUE TITLE
spaces

### ISSUE THREAD

**Issue by SwampertX** [uschongensec/cinnabot#5]
![image](https://user-images.githubusercontent.com/17807016/56091585-551c0e80-5ee3-11e9-83d8-c07231e3938e.png)
spaces command is not consistent with results

**Comment by chloelee767** [comment]
I think I've fixed this! But I'll need to wait until there's an event to test on (Tues) to confirm.

**Comment by SwampertX** [comment]
Great job! Feel free to make a pull request, will review when I have time :)

**Comment by SwampertX** [comment]
closed by #8 .
